package com.enviro.assessment.grad001.asandilenkala.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;

/**
 * The WasteCategory class represents a waste category in the system.
 * It is a JPA entity mapped to a database table, where each instance corresponds to a row in the 'waste_category' table.
 */
@Entity
public class WasteCategory {

    // Unique identifier for the WasteCategory, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the waste category.
     * This attribute is required, and validation ensures it is not blank.
     * @param name the name of the waste category
     */
    @NotBlank(message = "Category name is required")
    private String name;

    /**
     * A description of the waste category.
     * This attribute is required, and validation ensures it is not blank.
     * @param description the description of the waste category
     */
    @NotBlank(message = "Description is required")
    private String description;

    /**
     * Gets the ID of the WasteCategory.
     * @return the ID of the WasteCategory
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the ID of the WasteCategory.
     * @param id the ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the name of the WasteCategory.
     * @return the name of the WasteCategory
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the WasteCategory.
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Gets the description of the WasteCategory.
     * @return the description of the WasteCategory
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the description of the WasteCategory.
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }
}
